# OBS: Não criei um novo arquivo chamado _config.yml, pois o mesmo já existia e não é possível criar com o mesmo nome.
collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"